---
- name: "Create custom fact directory"
  ansible.builtin.file:
    path: "/etc/ansible/facts.d"
    state: "directory"
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: "Set host facts"
  ansible.builtin.template:
    src: "host-info.fact.j2"
    dest: "/etc/ansible/facts.d/host-info.fact"
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: "Reload Custom Facts"
  setup:
    gather_subset: "local"
...
