---
name: Molecule Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-workflow-lint:
    uses: infra-monkey/reuseable_workflows/.github/workflows/ansible_role_lint.yml@main
  call-workflow-molecule-debian-bullseye:
    needs: call-workflow-lint
    uses: infra-monkey/reuseable_workflows/.github/workflows/ansible_role_molecule.yml@main
    with:
      image: 'debian'
      tag: 'bullseye'
  call-workflow-molecule-debian-bookworm:
    needs: call-workflow-lint
    uses: infra-monkey/reuseable_workflows/.github/workflows/ansible_role_molecule.yml@main
    with:
      image: 'debian'
      tag: 'bookworm'
  call-workflow-molecule-redhat-7:
    needs: call-workflow-lint
    uses: infra-monkey/reuseable_workflows/.github/workflows/ansible_role_molecule.yml@main
    with:
      image: 'redhat'
      tag: '7'
