---
name: Molecule Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-workflow-molecule:
    uses: infra-monkey/reuseable_workflows/.github/workflows/ansible_role_molecule.yml@main
    with:
      role-name: 'host_info_facts'
